const { fileHashLoader }  = require('./loadFileHashes');

const fileHashParser = (path) => { 
    let fileHashes = fileHashLoader(path);

    let keys = Object.keys(fileHashes);
    if (keys.length === 0) {
        throw new Error(`No hashes found in file: ${pathToFile}`);
    }

    //loop thorugh the keys and sort only the ones we want into new json object
    let sortedHashes = {};
    console.log(keys, sortedHashes, fileHashes);
    let map = {};
    keys.forEach(key => {
        // filter for the updated public js files and we want to exclude the minified files we are looking for hashes on the edited files and path to those files (if dev)
        if (key.startsWith('public/js/') && !key.startsWith('public/js/min/') && key.endsWith('.js')) {
            let k = key.split('/').pop(); // Get the file name
            sortedHashes[k] = {};
            sortedHashes[k].hash = fileHashes[key].hash;   
            //in production we only need the hash because we will serve all files from the minified folder which will be generated by the build process
            // in development we want the full path to the file so we can load it directly
            if(process.env.NODE_ENV == 'development') {
                sortedHashes[k].path = key.replace('public/js/', ''); // Store the full path in development mode
            }
        }

        // filter for the updated public css files and we want to exclude the minified files we are looking for hashes on the edited files and path to those files (if dev)
        if (key.startsWith('public/css/') && !key.startsWith('public/css/min/') && key.endsWith('.css')) {
            let k = key.split('/').pop(); // Get the file name
            sortedHashes[k] = {};
            sortedHashes[k].hash = fileHashes[key].hash;   
            //in production we only need the hash because we will serve all files from the minified folder which will be generated by the build process
            // in development we want the full path to the file so we can load it directly
            if(process.env.NODE_ENV == 'development') {
                sortedHashes[k].path = key.replace('public/css/', ''); // Store the full path in development mode
            }
        }

        if(key.indexOf("src/scss/custom-bootstrap.scss") !== -1) {
            sortedHashes['custom-bootstrap.css'] = {};
            sortedHashes['custom-bootstrap.css'].hash = fileHashes[key].hash;
            // Store the full path which is just 'custom-bootstrap.css'
            if(process.env.NODE_ENV == 'development') {
                sortedHashes['custom-bootstrap.css'].path = 'custom-bootstrap.css'; 
            }
        }

        if(key.indexOf('sw.js') !== -1) {
            sortedHashes['sw.js'] = {};
            sortedHashes['sw.js'].hash = fileHashes[key].hash;
            sortedHashes['sw.js'].path = 'sw.js'; // Store the full path which is just 'sw.js'
        }
    });

    return sortedHashes;
}


module.exports = { fileHashParser };